### ISSUE TITLE
Parse error on S050624-v50.txt

### ISSUE THREAD

**Issue by ceranco** [adwhit/itchy-rust#16]
I'm trying to parse `S050624-v50.txt` taken from `sftp://itchdata.nasdaq.com:itchfiles_v5` but am getting an error on message 417848018. Running the `full_parse` test with the file returns:
> Mesaage 417848018 failed to parse: Parse error: Alt, buffer context [0, 50, 73, 0, 199, 0, 0, 52, 100, 53, 158, 254, 125, 0, 0, 0, 0, 0, 0, 0]

I'm happy to try and contribute a fix, but am not sure how to go about debugging this and would appreciate any advice.

**Comment by adwhit** [comment]
Without looking any more deeply, the most likely cause is a new message type that has been added since I last updated this codebase. If you can share the file (or just the specific message bytes) I could take a look. If you want to debug it yourself you'll want to isolate the message bytes and follow the parser step-by-step. Can't really recall how to do that at the moment, you'll probably need to check out the `nom` docs

**Comment by ceranco** [comment]
Thanks for the tips :)
Looking more deeply at the buffer context, I found that it was a missing `CrossType`  in the `NOII` message. I'll open a PR with the fix.

**Comment by adwhit** [comment]
Cool! Have pushed the fix in `0.3.1`
